//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JP.Exactus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int IDAuditoria { get; set; }
        public int IDDispositivo { get; set; }
        public string DescripcionAccion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
    }
}
