//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JP.Exactus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dispositivo()
        {
            this.Auditoria = new HashSet<Auditoria>();
        }
    
        public int IDDispositivo { get; set; }
        public int IDEmpresa { get; set; }
        public string NombreDispositivo { get; set; }
        public string MACDispositivo { get; set; }
        public System.DateTime FechaExpira { get; set; }
        public bool Activo { get; set; }
        public int UsuarioModifica { get; set; }
        public System.DateTime FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditoria { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
