//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JP.Exactus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Empresas
    {
        public int Emp_Id { get; set; }
        public string Emp_Nombre { get; set; }
        public Nullable<System.DateTime> Emp_Ingreso { get; set; }
    }
}
