//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JP.Exactus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opciones()
        {
            this.OpcionesEmpresa = new HashSet<OpcionesEmpresa>();
        }
    
        public int IDOpcion { get; set; }
        public string DescripcionOpcion { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpcionesEmpresa> OpcionesEmpresa { get; set; }
    }
}
